=== mohamed0aymane/bank/bank-backend/app/src/data/banque.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  
  <xs:simpleType name="EmailAgentType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9]+@gmail\.com"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="EmailManagerType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z]+\.[a-z]+@mhabank\.com"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="TelephoneType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="RoleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="manager"/>
      <xs:enumeration value="agent"/>
    </xs:restriction>
  </xs:simpleType>

 
  <xs:simpleType name="StatutType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="active"/>
      <xs:enumeration value="desactive"/>
    </xs:restriction>
  </xs:simpleType>

  
  <xs:simpleType name="DeviseType">
    <xs:restriction base="xs:string">
      <xs:pattern value="dh"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- ====================== UTILISATEURS ====================== -->

  <xs:complexType name="UtilisateurManagerType">
    <xs:sequence>
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="prenom" type="xs:string"/>
      <xs:element name="role" default="manager"/>
      <xs:element name="email" type="EmailManagerType"/>
      <xs:element name="telephone" type="TelephoneType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="UtilisateurAgentType">
    <xs:sequence>
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="prenom" type="xs:string"/>
      <xs:element name="role" fixed="agent"/>
      <xs:element name="email" type="EmailAgentType"/>
      <xs:element name="telephone" type="TelephoneType"/>
    </xs:sequence>
    
  </xs:complexType>

  <xs:element name="utilisateurs">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="manager" type="UtilisateurManagerType"/>
        <xs:element name="agent" type="UtilisateurAgentType"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <!-- ====================== COMPTE ====================== -->

  <xs:complexType name="CompteType">
    <xs:sequence>

    
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="prenom" type="xs:string"/>
      <xs:element name="email" type="EmailAgentType"/>

      <xs:element name="numero" type="TelephoneType"/>
      <xs:element name="type" type="xs:string"/>

      <xs:element name="solde">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.00"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="devise" type="DeviseType"/>
      <xs:element name="dateCreation" type="xs:date"/>
      <xs:element name="statut" type="StatutType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    
  </xs:complexType>

  <xs:element name="comptes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="compte" type="CompteType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>



  <xs:element name="banque">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="utilisateurs"/>
        <xs:element ref="comptes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mohamed0aymane/bank/bank-backend/app/src/data/banque.xml
<?xml version="1.0" encoding="UTF-8"?>
<banque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="banque.xsd">

  <utilisateurs>

    <manager>
      <nom>Lamhamdi</nom>
      <prenom>Aymane</prenom>
      <role>manager</role>
      <email>lamhamdi.aymane@mhabank.com</email>
      <telephone>0612345678</telephone>
    </manager>

   

  </utilisateurs>

  <comptes>

    <compte id ="C004">
     
      <nom>Lamhamdi</nom>
      <prenom>Aymane</prenom>
      <email>aymane@gmail.com</email>
      <numero>0700000007</numero>
      <type>courant</type>
      <solde>12500.75</solde>
      <devise>dh</devise>
      <dateCreation>2024-09-01</dateCreation>
      <statut>active</statut>
    </compte>

  </comptes>

</banque>
